defaultIndent: "\t"
backupExtension: .bak
onlyOneBackUp: 1
indentPreamble: 0
lookForAlignDelims:
   tabular: 1
   tabularx: 1
   longtable: 1
   array: 1
   matrix: 1
   align: 1
   align*: 1
   aligned: 1
   cases: 1
oneSentencePerLine:
   manipulateSentences: 1
removeTrailingWhitespace:
   beforeProcessing: 0
   afterProcessing: 1
indentAfterItems:
   itemize: 1
   enumerate: 1
   description: 1
   list: 1
indentAfterHeadings:
   part:
      indentAfterThisHeading: 0
      level: 1
   chapter:
      indentAfterThisHeading: 0
      level: 2
   section:
      indentAfterThisHeading: 1
      level: 3
   section*:
      indentAfterThisHeading: 1
      level: 3
   subsection:
      indentAfterThisHeading: 1
      level: 4
   subsection*:
      indentAfterThisHeading: 1
      level: 4
   subsubsection:
      indentAfterThisHeading: 1
      level: 5
   paragraph:
      indentAfterThisHeading: 1
      level: 6
   subparagraph:
      indentAfterThisHeading: 1
      level: 7
noAdditionalIndent:
   myexample: 1
   mydefinition: 1
   problem: 1
   exercises: 1
   mysolution: 1
   foreach: 0
   widepage: 1
   comment: 1
   document: 1
   frame: 0
