repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
      args: ["--maxkb=1000"]
    - id: check-merge-conflict
  - repo: https://github.com/jonasbb/pre-commit-latex-hooks
    rev: v1.4.3
    hooks:
      - id: cleveref-capitalization
      - id: consistent-spelling
        args:
            [
              "--emph=et al.",
              "--emph=a priori",
              "--emph=a posteriori",
              '--regex=naive=\bna(i|\\"i)ve',
              "--regex=deeplearning=\bdeep( |-)learning"
            ]
      - id: csquotes
      - id: no-space-in-cite
  # - repo: https://github.com/FlamingTempura/bibtex-tidy
  #   rev: 9658d907d990fd80d25ab37d9aee120451bf5d19
  #   hooks:
  #     - id: bibtex-tidy
  #       args:
  #         - --v2
  #         - --modify
  #         - --curly
  #         - --space=4
  #         - --align=14
  #         - --duplicates
  #         - --escape
  #         - --remove-empty-fields
  - repo: local
    hooks:
      - id: chktex
        name: Checking Tex document with ChkTeX
        entry: chktex
        language: system
        types: [file, tex]
        args:
          - -v1
          - -d4
      - id: lacheck
        name: Checking Tex document with lacheck
        entry: lacheck
        language: system
        types: [file, tex]
      - id: latexindent
        name: Indent LATEX documents
        entry: latexindent
        language: system
        types: [file, tex]
        args:
          - -wd
          - -s
          - -c ./.latexindent.bak/
