name: Compile Thesis manuscript
on:
  push:
    branches:
      - main
    tags:        
      - '**'
    paths:
      - "**.tex"
      - "**.cls"
      - "**.bib"
      - "**.pdf"
      - "**.csv"
permissions:
  contents: write
jobs:
  compile:
    name: Printed version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - run: echo "CLASS_LINE=$(grep -n '\documentclass' ${{ github.workspace }}/main.tex  | cut -d ':' -f 1)" >> $GITHUB_ENV
      - run: sed "${{ env.CLASS_LINE }}s/.*/\\\documentclass\[print,english,final\]\{thesissaclay\}/" ${{ github.workspace }}/main.tex > thesis_print.tex
      - run: sed "${{ env.CLASS_LINE }}s/.*/\\\documentclass\[web,english,final\]\{thesissaclay\}/" ${{ github.workspace }}/main.tex > thesis_web.tex
      - name: Compile documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            ${{ github.workspace }}/thesis_print.tex
            ${{ github.workspace }}/thesis_web.tex
          latexmk_use_xelatex: true
          work_in_root_file_dir: false
          args: -outdir=${{ github.workspace }}/PDF/ -interaction=nonstopmode -file-line-error -halt-on-error
          docker_image: ghcr.io/xu-cheng/texlive-full:20240605
          pre_compile: mkdir -p PDF/{chapters,appendix,frontmatter,preamble} && python -m venv /root/venv/ && cd .devcontainer/PygmentsFlexoki && /root/venv/bin/pip install . && cd - && echo "main_memory = 7999999" >> /opt/texlive/texdir/texmf.cnf && fmtutil-sys --all
      - name: Release Documents
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/PDF/thesis_web.pdf
            ${{ github.workspace }}/PDF/thesis_print.pdf
          draft: false
          body: TEMP
          tag_name: ${{ github.ref }}
          make_latest: true
          name: Compiled PDFs
