name: Compile Thesis manuscript
on:
  push:
    branches:
      - writing
    paths:
      - "**.tex"
      - "**.cls"
      - "**.bib"
      - "**.pdf"
      - "**.csv"
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38.2"
      - run: perl scripts/gitinfo2.pm 
      - name: Restore cached Figures
        id: figures-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: PDF/robustExternalize
          key: figuresCache
      - name: Compile full document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            ${{ github.workspace }}/main.tex
            ./chapters/1-Introduction.tex
            ./chapters/2-Background.tex
            ./chapters/3-SOTA.tex
            ./chapters/4-AttOmics.tex
            ./chapters/5-CrossAttOmics.tex
            ./chapters/6-CrossAttOmicsGate.tex
            ./chapters/7-Interpretability.tex
            ./chapters/8-Conclusions.tex
          latexmk_use_xelatex: true
          work_in_root_file_dir: false
          args: -outdir=${{ github.workspace }}/PDF/ -interaction=nonstopmode -file-line-error -halt-on-error
          docker_image: ghcr.io/xu-cheng/texlive-full:20240605
          pre_compile: mkdir -p PDF/{chapters,appendix,frontmatter,preamble} && python -m venv /root/venv/ && cd .devcontainer/PygmentsFlexoki && /root/venv/bin/pip install . && cd - && echo "main_memory = 7999999" >> /usr/local/texlive/2024/texmf.cnf && fmtutil-sys --all
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.10' 
      # - name: Cleaning cache
      #   run: cd PDF/ && python robExt-remove-old-figures.py
      - name: Save Figures
        id: figures-cache-save
        uses: actions/cache/save@v4
        with:
          path: PDF/robustExternalize
          key: ${{ steps.figures-cache-restore.outputs.cache-primary-key }}
      - name: Release PDF files
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/PDF/main.pdf
            ${{ github.workspace }}/PDF/1-Introduction.pdf
            ${{ github.workspace }}/PDF/2-Background.pdf
            ${{ github.workspace }}/PDF/3-SOTA.pdf
            ${{ github.workspace }}/PDF/4-AttOmics.pdf
            ${{ github.workspace }}/PDF/5-CrossAttOmics.pdf
            ${{ github.workspace }}/PDF/6-CrossAttOmicsGate.pdf
            ${{ github.workspace }}/PDF/7-Interpretability.pdf
            ${{ github.workspace }}/PDF/8-Conclusions.pdf
          draft: true
          name: Writing Drafts
