name: On demand compilation
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Final or draf version'
        required: true
        default: final
        type: choice
        options:
        - final
        - draft
      type:
        description: Printed or web version
        required: true
        default: web
        type: choice
        options:
        - web
        - print
      gitmark:
        description: 'Include git commit in document'
        required: true
        type: boolean
env:
  DOC_OPTIONS: ${{ inputs.version }},${{ inputs.type }},${{ inputs.gitmark && 'gitmark' || ''}}
jobs:
  compile_chapter:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38.2"
      - run: perl scripts/gitinfo2.pm 
      - run: echo "CLASS_LINE=$(grep -n '\documentclass' ${{ github.workspace }}/main.tex  | cut -d ':' -f 1)" >> $GITHUB_ENV
      - run: sed -i "${{ env.CLASS_LINE }}s/.*/\\\documentclass\[$DOC_OPTIONS\]\{thesissaclay\}/" ${{ github.workspace }}/main.tex 
      - run: head -n 10 main.tex
      - name: Compile ${{ inputs.file }}
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          work_in_root_file_dir: false
          args: -outdir=${{ github.workspace }}/PDF/ -interaction=nonstopmode -file-line-error -halt-on-error
          docker_image: ghcr.io/xu-cheng/texlive-full:20240605
          pre_compile: mkdir -p PDF/{chapters,appendix,frontmatter,preamble} && python -m venv /root/venv/ && cd .devcontainer/PygmentsFlexoki && /root/venv/bin/pip install . && cd - && echo "main_memory = 7999999" >> /opt/texlive/texdir/texmf.cnf && fmtutil-sys --all
      - name: Save generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}-${{ inputs.file }}
          path: ${{ github.workspace }}/PDF/main.pdf
          retention-days: 1
          overwrite: true